#!/bin/bash

DEFAULT_ACCT=${AWS_ACCOUNT_ID}
DEFAULT_FUNC=LambdaFunctionOverHttps
DEFAULT_FILE=LambdaFunctionOverHttps.zip
DEFAULT_ROLE="lambda-gateway-execution-role"
DEFAULT_RUNTIME=nodejs4.3
DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
DEFAULT_INPUT=input.json
DEFAULT_QUERY=""
DEFAULT_OUTPUT=output.json
DEFAULT_TYPE=RequestResponse
DEFAULT_TIMEOUT=30
DEFAULT_GATEWAY=DynamoDBOperations
DEFAULT_DESCRIPTION="REST API for DynamoDB operations"
DEFAULT_RESOURCE=DynamoDBManager
DEFAULT_PARENT="/"
DEFAULT_METHOD=POST
DEFAULT_AUTH=NONE
DEFAULT_STATUS=200
DEFAULT_STAGE=prod
DEFAULT_TABLE=data
DEFAULT_POLICY=dynamoDbUpolad
DEFAULT_POLICY_DESCRIPTION="Allow upload of items into DynamoDB table"
